### ISSUE TITLE
Support for Windows? 

### ISSUE THREAD

**Issue by dhbloo** [nkg114mc/c-gomoku-cli#1]
Glad to see a cli tool for gomoku engines.
Is there any plan to add support for Windows? Since most gomocup engines only have Windows executable, it would be much more useful being able to run on Windows. 😀

**Comment by nkg114mc** [comment]
Hi Haobin,
Thanks for the message! I am thinking about the Windows support. But since it is derived from c-chess-cli, there is some Linux/Unix process related code that is non-trivial to be converted to Windows. Most of them is located at `engine.cpp`. So it may take me a while to learn all the knowledge about Windows system programming first before implementing it. Since Piskvork is available under Windows, at least engine developers already have some tools in hand at this moment, so it is not too bad though :)

**Comment by lucasart** [comment]
Nice work @dhbloo. I will probably integrate this in c-chess-cli.

Regarding `getc_unlocked()`, if you are serious about switching to C++, you should simply get rid of `str_getline()`, and use instead `std::getline()`. This will force you to use `std::string` instead of `char *`. You can easily do the conversion when needed, and gradually switch the whole codebase to std::string, and get rid of the `str.*` source files.

Same goes for `vec.*`. Obviously, you should use `std::vector<>` in C++.

**Comment by dhbloo** [comment]
Yes I think we will gradualy refactor the code base to pure C++. However this might take us a long time to do it, since it works fine now and refactoring means a lot of work which none of us have spare efforts to do this now. 😂
